[features]
seeds = false
skip-lint = false
[programs.localnet]
bonk_mint = "BoNk8h5Nk687Mag3mMnGTsDMePi6JwimSFZjQP7vBNZs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet" 
wallet = "/Users/fzzyyti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "mpl_metadata.so"
